//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography;
using System.Text;

namespace OneTimeSecret_Clone.Models
{
    public class secretTable
    {
        
        private int id { get; set; }
        
        [Required]
        [Display(Name = "Tu secreto")]
        public string secret { get; set; }

        [Required]
        [Display(Name = "Tu palabra secreta")]
        public string hash { get; set; }
        public static string HashGenerator(string input)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] inputBytes = Encoding.UTF8.GetBytes(input);
                byte[] hashBytes = sha256.ComputeHash(inputBytes);
                StringBuilder sb = new StringBuilder();

                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2"));
                }

                return sb.ToString();
            }

        }
    }
}